services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    env_file: .env
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - 4242:4242
    volumes:
      - ./containers/nestjs/:/nestjs/code/
    depends_on:
      - vuejs # Prevents npm ci timeout
      - db

  vuejs:
    build: containers/vuejs
    image: vuejs
    container_name: vuejs
    env_file: .env
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - 2424:2424
    volumes:
      - ./containers/vuejs/:/vuejs/code/

  db:
    image: postgres:alpine
    container_name: db
    env_file: .env
    ports:
      - 5432:5432 # Used to manually inspect the db from the host
    volumes:
      - db_volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_volume:
