services:
  nestjs:
    build: containers/nestjs
    image: nestjs
    container_name: nestjs
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - "4242:4242"
    volumes:
      - ./containers/nestjs:/nestjs

  vuejs:
    build: containers/vuejs
    image: vuejs
    container_name: vuejs
    init: true # Prevents waiting on 10s timeout on shutdown
    restart: on-failure
    ports:
      - "2424:2424"
    volumes:
      - ./containers/vuejs:/vuejs

  # db:
  #   image: postgres:alpine
  #   container_name: db
  #   env_file: .env
